[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

# Remappings for OpenZeppelin
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Add this section for Hedera Testnet
[rpc_endpoints]
testnet = "${HEDERA_RPC_URL}"
mainnet = "https://mainnet.hashio.io/api"

# Etherscan API configuration for Hedera (Hashscan)
[etherscan]
testnet = { key = "none", chain = 296, url = "https://server-verify.hashscan.io/" }
